---
:last_used_folder: C:/Users/MonteneL/VSCodeProjects/cdos/Extracted files Castlevania
  - Alvor da Tristeza (BR)
:tiled_path: ''
:emulator_path: C:/Users/MonteneL/data/e/nds/melonDS/melonDS.exe
:gba_emulator_path: ''
:test_room_save_file_index: 0
